### ISSUE TITLE
Write Scripts to answer the questions from the meeting with Sana

### ISSUE THREAD

**Issue by MsPockets** [codeforboston/clean-slate#154] opened 2020-07-01 00:29 UTC
Something that we are able to continually work toward no matter the state of the data is writing scripts to answer the questions in #152 

For clarification: The first question and each subsection `a)` of questions 2 and 3 are based on the current law, and subsection `b)` is what the questions would change to if the law changes in the coming months.

**Comment by jeremylang** [comment] 2020-09-08 23:53
Considering this duplicate of #152 since the work it doesn't seem to need multiple trackers.

**Closed by jeremylang** 2020-09-08 23:53 UTC
Labels: data
